[2025-10-06T20:32:45.279+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: regression_pipeline_dag.load_model_task manual__2025-10-06T20:32:34.326728+00:00 [queued]>
[2025-10-06T20:32:45.283+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: regression_pipeline_dag.load_model_task manual__2025-10-06T20:32:34.326728+00:00 [queued]>
[2025-10-06T20:32:45.283+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-06T20:32:45.283+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-10-06T20:32:45.283+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-06T20:32:45.288+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_model_task> on 2025-10-06 20:32:34.326728+00:00
[2025-10-06T20:32:45.291+0000] {standard_task_runner.py:55} INFO - Started process 6435 to run task
[2025-10-06T20:32:45.294+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'regression_pipeline_dag', 'load_model_task', 'manual__2025-10-06T20:32:34.326728+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp63p091ra']
[2025-10-06T20:32:45.295+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask load_model_task
[2025-10-06T20:32:45.322+0000] {task_command.py:388} INFO - Running <TaskInstance: regression_pipeline_dag.load_model_task manual__2025-10-06T20:32:34.326728+00:00 [running]> on host 378432d0311b
[2025-10-06T20:32:45.354+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abhinav
AIRFLOW_CTX_DAG_ID=regression_pipeline_dag
AIRFLOW_CTX_TASK_ID=load_model_task
AIRFLOW_CTX_EXECUTION_DATE=2025-10-06T20:32:34.326728+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-06T20:32:34.326728+00:00
[2025-10-06T20:32:45.362+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/lab.py", line 95, in load_model_elbow
    predictions = model.predict(X_test_scaled)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 362, in predict
    return self._decision_function(X)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/linear_model/_base.py", line 345, in _decision_function
    X = self._validate_data(X, accept_sparse=["csr", "csc", "coo"], reset=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 585, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/home/airflow/.local/lib/python3.7/site-packages/sklearn/base.py", line 401, in _check_n_features
    f"X has {n_features} features, but {self.__class__.__name__} "
ValueError: X has 2 features, but LinearRegression is expecting 1 features as input.
[2025-10-06T20:32:45.368+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=regression_pipeline_dag, task_id=load_model_task, execution_date=20251006T203234, start_date=20251006T203245, end_date=20251006T203245
[2025-10-06T20:32:45.374+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task load_model_task (X has 2 features, but LinearRegression is expecting 1 features as input.; 6435)
[2025-10-06T20:32:45.392+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-06T20:32:45.403+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
